function f=sk(u,g)
global ixp ixm iyp iym h;
f=((u(ixp,:,1)+u(:,:,1)).*g(ixp,:)...
  -(u(ixm,:,1)+u(:,:,1)).*g(ixm,:)...
  +(u(:,iyp,2)+u(:,:,2)).*g(:,iyp)...
  -(u(:,iym,2)+u(:,:,2)).*g(:,iym))/(4*h);
