function f=sk(param,u,g)
% global ixp ixm iyp iym h;
f=((u(param.ixp,:,1)+u(:,:,1)).*g(param.ixp,:)...
  -(u(param.ixm,:,1)+u(:,:,1)).*g(param.ixm,:)...
  +(u(:,param.iyp,2)+u(:,:,2)).*g(:,param.iyp)...
  -(u(:,param.iym,2)+u(:,:,2)).*g(:,param.iym))/(4*param.h);
